version: "3"
services:
    doggrdb:
        container_name: doggrdb
        image: mongo
        volumes:
            - /data/doggrdb:/data/db # this is format of host_path:container_path
    postgres:
        container_name: postgres
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=doggrdb
            - POSTGRES_USER=doggr_user
            - POSTGRES_PASSWORD=doggr_pass
    backend:
        container_name: backend
        build: ./backend/
        restart: always
        ports:
            - "9000:9000" # This will be the ONLY port exposed externally anywhere
        depends_on: #This is a lie
            - doggrdb
            - postgres
    frontend:
       container_name: frontend
       build: ./frontend/
       volumes:
            - './frontend:/app' # This pulls in all of our code and mounts it
            - '/app/node_modules' #This prevents us from copying our node_modules when mounting
       ports:
            - 3000:3000

